### ISSUE TITLE
Recommended implementation

### ISSUE THREAD

**Issue by danmckeon** [ungap/custom-elements#1]
I've been using the `document-register-element` polyfill to target IE11 and used the recommended implementation on that README: 

```
<script>this.customElements||document.write('<script src="//unpkg.com/document-register-element"><\x2fscript>');</script>
```

Do you still recommend using that same paradigm (`document.write`) with the new version of the polyfill? If I use the implementation on the README (with no `document.write`), it appears it would download the bundle for all browsers, not just ones missing `customElements`.

Also, are there any breaking changes to be aware of migrating from `document-register-element` to this package? I also use `hyperHTML-element` if that is a consideration.

Thanks for contributing all this great open source content supporting custom elements.

**Comment by WebReflection** [comment]
if you are not using builtin extend, you can use the same `<script>` but point at `//unpkg.com/@webreflection/custom-elements-no-builtin` instead, or simply point at this poly.

we use hyperHTML/Element in production and recently swapped polyfill ... it turned out HyperHTMLELement had an issue, and it got fixed, but the polyfill is rock solid.

I hope this answered your question.
