### ISSUE TITLE
[Safari] Lifecycle hooks of safari are not in sync with Chrome

### ISSUE THREAD

**Issue by kkkmr** [ungap/custom-elements#12]
In chrome, when element is appended to DOM and after that if attribute is changed, connectedCallback is called first and later attributeChangedCallback is called. 
However in safari (along with the latest polyfill), when element is appended and then attribute is changed, attributeChangedCallback is called first and later connectedCallback is called.

I am attaching the screenshots to show the behavior in chrome and safari respectively.
![chrome](https://user-images.githubusercontent.com/31439326/164199729-bde09cc8-f910-4a26-b37c-9311ad061fd9.png)
![safari](https://user-images.githubusercontent.com/31439326/164213136-758fb19e-7ff5-4d5a-8f02-68edaed16823.jpeg)

You can also check the sequence of console logs of given jsfiddle for the reference.
[jsFiddle link](https://jsfiddle.net/kkkmr/c0vbqsa7/1/)

**Comment by WebReflection** [comment]
the polyfill is based on mutation observer, one for attributes and one for generic document operations, so this won't be fixed.

what could be fixed, is a smelly logic based on what fires first, because a node can be appended or removed with or without attributes changing, so that trusting one happening before another is a code smell, imho.
