### ISSUE TITLE
Mistake in source code

### ISSUE THREAD

**Issue by kapouer** [ungap/custom-elements#20]
https://github.com/WebReflection/custom-elements/blob/0acfb63eab710719e84ba8773f0af689f091dbfd/template/index.js#L9

**Comment by WebReflection** [comment]
it's here indeed https://github.com/ungap/custom-elements/blob/master/index.js#L373

**Comment by WebReflection** [comment]
do you have any specific problem though? I think current state works with both old and newer Safari and the fix went in and it got tested to work everywhere ... I am saying this because while I fully agree there is a typo, I don't know enough of their internal changes to be sure if I change that, we'll have new issues on Safari.

**Comment by kapouer** [comment]
No I have nothing to say more :) just that it's a bug waiting to happen, probably.

**Comment by WebReflection** [comment]
AFAIK so far no browser complained, but I hear you ... although things work now. I will eventually fix this and push major (or minor, if I am still behind `0`) so let's hope that won't crash the world once that happens.

**Comment by kapouer** [comment]
Unfortunately I recently canceled my browserstack subscription. Do you know you can ask them to give this project free open source subscription ?

**Comment by WebReflection** [comment]
I have one already, that's why I've said, everything is fine.

**Comment by kapouer** [comment]
Since epiphany-browser is kind of webkit, I gave it a try...
@ungap/custom-elements 1.2.0 works there, but not version 1.3.0.

**Comment by WebReflection** [comment]
Imagine I use GNOME Web as my daily driver

**Comment by kapouer** [comment]
Well then that's odd. I'm diffing v1.2.0 / v1.3.0 to see what broke my setup

**Comment by kapouer** [comment]
Ha damn again it's a problem on my side. I'm loading the polyfill somewhat too late.

**Comment by kapouer** [comment]
FWIW my issue was that I was detecting the need to load the customElement polyfill using this code:
```
'customElements' in window && (function() {
 try {
  const BR = class extends HTMLBRElement {};
  const is = 'extends-br';
  customElements.define(is, BR, { extends: 'br' });
  return document.createElement('br', {is}).outerHTML.indexOf(is) > 0;
 } catch(e) {
  return false;
 }
})()
```
Which makes the corresponding detections fail in @ungap/custom-element, because extends-br is already registered.
~This code should really clean after itself.~ EDIT: https://github.com/WICG/webcomponents/issues/754 it cannot.

**Comment by WebReflection** [comment]
> I was detecting the need to load the customElement polyfill using this code:

The best way to run this polyfill for Safari or WebKit only is to stick this inline script as the first one on any page (within the `<head>`, of course):

```html
<script>
if (!(self.chrome || self.netscape))
  document.write('<script src="https://cdn.jsdelivr.net/npm/@ungap/custom-elements/es.js"></'+'script>');
</script>
```

arguably you can use the same trick to bring in just https://cdn.jsdelivr.net/npm/@webreflection/custom-elements-builtin/es.js without even needing to feature-detect as it's clear at this point Apple won't ever implement builtin extends.

**Comment by WebReflection** [comment]
**CodePen Live Demo** https://codepen.io/WebReflection/pen/wvNzOmr?editors=1000

**Comment by kapouer** [comment]
Thanks for the additional infos. However I'm loading a bunch of other polyfills (mostly from polyfill.io's detectSource fields) before actually executing my library. It's a bit convoluted but it avoids user-agent detection, and all polyfills are equal :)

**Comment by WebReflection** [comment]
I haven't used user agent sniffing, I've used proprietary fields per browser ... I am not parsing a string, I am checking the env :wink: 

Like I've said, that is the best way to land this poly for Safari only and no network request even ever happens in Chrome or Firefox ... the CDN caches that too so it's irrelevant for your users.

In short, do what you want, but the best wayfor **this** polyfil *is* the one I've suggested there, actually the CodePen example is even better because it doesn't trash any entry in the `customElements` registry at all so it never conflicts, not even if other projects embed this polyfil as the polyfil will pass the feature detection after the first patch so ... it's all good.
